version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: deptno/circleci-awscli-node8:0.1
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: v1-npm-deps-{{ checksum "package.json" }}
      - run: yarn
      - run: yarn format:all
      - run: yarn yarn lint:all
      - save_cache:
          key: v1-npm-deps-{{ checksum "package.json" }}
          paths:
            - node_modules